#Parte 1 
from tkinter.tix import REAL


Definir MEDIA (n1: REAL, n2: REAL, n3: REAL) REAL #DEFINIMOS LA FUNCIÓN SUMA
    suma = n1 + n2 + n3 #INICIALMENTE NUESTRA FUNCIÓN SUMA LOS TRES PARÁMETROS APORTADOS
    media = suma/ 3 #NUESTRA FUNCIÓN DIVIDE EL RESULTADO DE SUMA ENTRE 3 PARA OBTENER LA MEDIA
resultado = suma #NUESTRA FUNCIÓN NOS DEVUELVE LA MEDIA DE LOS TRES NÚMEROS QUE SE INTRODUCEN EN LA MISMA